### ISSUE TITLE
shouldn't vega3 be removed from requirements.txt ?

### ISSUE THREAD

**Issue by stonebig** [jakevdp/pdvega#30]
vega3 is marked as decrepited, if I understood well.

**Comment by domoritz** [comment]
See https://github.com/jakevdp/pdvega/pull/24

**Comment by stonebig** [comment]
ok, a duplicate. just noticed current official pdvega wheel was still requiring vega3.

**Comment by stonebig** [comment]
the installation.html also still refers to vega 3:
````
jupyter nbextension install --sys-prefix --py vega3
````
