### ISSUE TITLE
module 'pandas.core' has no attribute 'index'

### ISSUE THREAD

**Issue by uli22** [jakevdp/pdvega#47]
trying to use pdvega like in  documentation anytime I get the error message 'module 'pandas.core' has no attribute 'index''
e.g. 
import numpy as np
import pandas as pd
import pdvega
from vega_datasets import data
iris = data.iris()
pdvega.andrews_curves(iris, 'species')

I am using python 3.8
I think it is because pandas deprecated index

**Comment by domoritz** [comment]
Could this be related? https://github.com/vega/ipyvega/issues/203

**Comment by jakevdp** [comment]
pdvega is based on a very old version of Vega-Lite, and I don't have plans to continue developing it. A better replacement that covers the same use-case is https://github.com/altair-viz/altair_pandas, though it's not being actively developed at the moment either (anyone interested in taking over?)
